### ISSUE TITLE
Blog Übersicht

### ISSUE THREAD

**Issue by alexsuter** [alexsuter/travel-blog#1]
Als Benutzer möchte ich alle TravelBlogs sehen, sodass ich dasjenige, das mich interessiert
auswählen kann.

Akzeptanz Kriterien
• Alle Blogs sind aufgelistet.
• Pro Blog wird Titel, Destination und eine Kurzbeschreibung angezeigt.

**Comment by alexsuter** [comment]
@wuethrich44 
- Ich habe bereits diverse Sachen definiert, siehe Wiki (https://github.com/alexsuter/travel-blog/wiki). Falls was nicht passt, einfach anpassen.
- Layouting habe ich noch nichts gemacht. Sollen wir Bootstrap verwenden?

**Comment by wuethrich44** [comment]
Habe noch ein bis zwei Verbesserungen hinzugefügt aber sonst sieht es super aus. 

Für das Layout würde ich gerne mal [Foundation](http://foundation.zurb.com/) ausprobieren.
