### ISSUE TITLE
Neuer Eintrag

### ISSUE THREAD

**Issue by alexsuter** [alexsuter/travel-blog#5]
Als Blogger möchte ich einen neuen Eintrag zu einem (zum letzten ?) Blog hinzufügen.

Akzeptanz Kriterien
• Der neue Eintrag erscheint im letzten Blog.
• Andere Einträge sind unverändert.

**Comment by wuethrich44** [comment]
![image](https://cloud.githubusercontent.com/assets/6050639/15119295/84d6a23a-1610-11e6-9643-c713e581937b.png)
