### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by wuethrich44** [alexsuter/travel-blog#9]

**Comment by alexsuter** [comment]
@wuethrich44 
- Ich habe kein RBAC gemacht, gemäss Anforderungen nur in "Zukunft" benötigt. Ist man authentifiziert, dann kann man die Daten bearbeiten und sonst nur anschauen.
- Ich habe eine Komponente und einen Intereceptor gemacht. Hoffe das passt einigermassen.
- Die Mutations-Routen habe ich auf dem Server nun schon geschützt.

- Du kannst auf deinem System Test-Benutzer anlegen mit: GET /api/user/setup

```javascript
var users = [
   { username: "alex", password: "1234" },
   { username: "fabian", password: "4321" }
]
```
